In [1]:
import numpy as np

In [2]:
#数组构建
np.array([[1,2,3],[2,3,4]])#正常构建
np.ones(3)#全一数组
np.zeros(3)#全零数组
np.random.rand(2,3)#随机数数组
np.random.randint(2,3)#随机整数数组
np.linspace(start = 1,stop = 5,num = 5)#线性数组
np.arange(10, 0, -2)#最后一项为step
np.indices((3, 4), dtype=np.float64)#下标数组
np.empty((3,4))#空数组

array([[-2.21885393e+265,  1.07623317e-283,  5.24585216e-304,
         1.16722358e-279],
       [ 1.83140054e-077, -2.21885393e+265,  1.07623317e-283,
         5.24585216e-304],
       [ 1.16722358e-279,  1.83140054e-077, -2.21885393e+265,
         1.07623317e-283]])

In [3]:
#基本信息查询
a = np.array([[1,2,3],[2,3,4]])#正常构建
a.ndim
a.shape
a.size
a.dtype
a.itemsize

8

In [4]:
#改变形状
a.reshape(3,2)#a本身不改变
a.resize(3,2)#a改变
a.swapaxes(0,1)
a.flatten()

array([1, 2, 3, 2, 3, 4])

In [5]:
#算数运算函数
a = np.array([4,5,6])
b = np.array([1,2,3])

np.add(a,b)
np.subtract(a,b)
np.multiply(a,b)
np.divide(a,b)
np.floor_divide(a,b)
np.negative(a)
np.power(a,b)
np.remainder(a,b)#取模，即a%b

array([0, 1, 0])

In [6]:
#比较运算函数
a = np.array([4,1,2])
b = np.array([2,3,2])

np.equal(a,b)
np.not_equal(a,b)
np.less(a,b)
np.less_equal(a,b)
np.greater(a,b)
np.greater_equal(a,b)

array([ True, False,  True])

In [7]:
#数学计算函数
x = 5.5
np.abs(x)
np.sqrt(x)
np.square(x)
np.sign(x)
np.ceil(x)
np.floor(x)
np.rint(x)#round int
np.exp(x)
np.log(x),np.log2(x),np.log10(x)

(np.float64(1.7047480922384253),
 np.float64(2.4594316186372973),
 np.float64(0.7403626894942439))

In [8]:
#实践示例
import numpy as np
name = np.array([
    '小明',
    '小天',
    '小明',
    '小红',
    '小风',
    '小明',
    '小红',
    '小风',
    '小明',
    '小天',
    '小亮'
])

def unique_count(A):
    unique, inverse = np.unique(A, return_inverse=True)
    count = np.zeros(len(unique), dtype = int)
    np.add.at(count,inverse,1)
    return np.vstack((unique, count)).T

name_counts = unique_count(name)
print(name_counts)

total = name_counts[:,1].astype(int).sum() - 1

dcounts = dict(zip(name_counts[:,0],name_counts[:,1].astype(int) - 1))

sim_matrix = np.zeros((name.size,name.size),dtype = float)

x, y = sim_matrix.shape

for i in range(0,x):
    for j in range(0,y):
        if i != j:
            if name[i] == name[j]:
                sim_matrix[i][j] = dcounts[name[i]]/total
            else:
                sim_matrix[i][j] = 0
        else:
            sim_matrix[i][j] = 1

print(sim_matrix)


[['小亮' '1']
 ['小天' '2']
 ['小明' '4']
 ['小红' '2']
 ['小风' '2']]
[[1.  0.  0.3 0.  0.  0.3 0.  0.  0.3 0.  0. ]
 [0.  1.  0.  0.  0.  0.  0.  0.  0.  0.1 0. ]
 [0.3 0.  1.  0.  0.  0.3 0.  0.  0.3 0.  0. ]
 [0.  0.  0.  1.  0.  0.  0.1 0.  0.  0.  0. ]
 [0.  0.  0.  0.  1.  0.  0.  0.1 0.  0.  0. ]
 [0.3 0.  0.3 0.  0.  1.  0.  0.  0.3 0.  0. ]
 [0.  0.  0.  0.1 0.  0.  1.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0.1 0.  0.  1.  0.  0.  0. ]
 [0.3 0.  0.3 0.  0.  0.3 0.  0.  1.  0.  0. ]
 [0.  0.1 0.  0.  0.  0.  0.  0.  0.  1.  0. ]
 [0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1. ]]
